### ISSUE TITLE
It must be POST instead of GET

### ISSUE THREAD

**Issue by 04Shivam** [g1vi/AllTheWriteUps#1]
On Week 7. HTB - Napper.MD your screenshot of burpsuite is doing get request I performed it didn't work I tried post method it worked and the way you gave the parameters it must be post.

**Comment by g1vi** [comment]
Hi Shivam,
You are absolutely right. Considering the way the parameters are given, it must be a POST request. I just updated both screenshots.

Thanks for commenting!
